#+TITLE: org2wiz
#+OPTIONS: ^:{}

* 插件介绍
为知笔记的一款插件，使为知支持 org-mode。
* 插件安装
打包下载 repo 的 zip 压缩包，然后将 ~.zip~ 后缀改为 ~.wizplugin~ ，双击安装即可。
* 插件使用
org 文档标题必须以 ~.org~ 结尾。插入附件，后缀为 ~.org~ ，然后在为知笔记界面点击 ~org2wiz~ 。

感谢原作者 [[http://bbs.wiz.cn/space-uid-5130.html][@myflocky]]。
* 原插件问题
安装原版 ~Org-Mode插件~ 之后，按照应用描述进行操作会没有一点效果，操作之后还是一片空白。好心人 [[http://bbs.wiz.cn/space-uid-26363.html][@yangguang760]] 在 [[http://bbs.wiz.cn/forum.php?mod=redirect&goto=findpost&ptid=17135&pid=109573][帖子回复]] 中指出在这里需要对 ~Org-Mode插件~ 文件夹（ ~D:\MyDocuments\My Knowledge\Plugins\{a1f84253-8cba-4753-82c9-6654642c3c8c}~ ）下的 ~Org-Mode.js~ 文件作修改，修改方法见以上引用信息。其中 ~D:\MyDocuments~ 为我在本机安装数据文件夹的路径，请自行替换为自己电脑上为知笔记的数据文件夹路径。

#+BEGIN_QUOTE
新版org-mode的内置函数改了，所以插件的第30行应改为
#+BEGIN_SRC
strParam = " --batch -q --no-site-file --visit \""+OrgFile+"\" --funcall org-html-export-to-html";
#+END_SRC
本人已验证。
#+END_QUOTE

感谢好心人 [[http://bbs.wiz.cn/space-uid-26363.html][@yangguang760]] 给出了解决方案。
* 想法
下面是我根据我的部分需求和想法想让该插件实现的功能。只可惜我对这些没有经验，但会试着学习来实现这些功能，更希望能有感兴趣的道友一起实现这些功能。
** TODO 从 org 导出的 html 也支持 MathJax(本地/远程) （完成60%）
类似该插件支持的 markdown 导出之后仍然支持调用 MathJax 的功能。插件介绍说本身已经支持本地 MathJax 解析功能，但是我按照介绍的方法生成的 html 没有被渲染。可以选择调用本地的 MathJax 还是远程的 MathJax。
** TODO 自动识别附件中需要导出的那个 org 文件 （完成 50%）
附件中有时候不会只放置所需的 org 文件，有时候会加入一些其他附件，这个时候附件的自动排序会导致插件的导入 org 功能失效。此时必须手动修改 org 文件名，很不方便，也不智能。

我的想法是：如果附件中只有一个 org 文件，就让该插件自动识别已添加的附件，并找出所需的 org 文件，然后进行 Org2Wiz 操作；如果有多个 org 文件会让使用者选择需要导出的 org 文件，否则就导出默认的那个文件（该功能还需要进行更周全的考虑）。
** CANCELLED Org2Wiz 支持利用为知的导入 pdf 功能实现把 org 通过 tex 导出的 pdf 文件导入当前笔记中
CLOSED: [2016-07-16 Sat 03:04]
:LOGBOOK:
- State "CANCELLED"  from "TODO"       [2016-07-16 Sat 03:04] \\
  为知不提供导入文件相关 API。
:END:
功能构思：org 常用的导出格式为 html 和 pdf(经过 LaTeX)，而 pdf 格式对公式的支持比 MathJax 好。因此想要实现可以选择导出 html 还是导出 pdf 到该笔记中。为知支持 pdf 导入，但是好像知道只可以导入到新笔记中，需要更仔细的调研。

这个功能还涉及到 org 中针对 html 和 pdf 导出的相关设置，暂时不重点考虑，假设导出时这部分设置已经完善。

由于为知未开放导入文件相关的 API，所以暂时这个想法不能实现了。
** DONE 自动把当前文件夹同名的 pdf 和 tex 文件加入到附件中（设置 AttachmentsOption=1）
CLOSED: [2016-07-17 Sun 17:44]
:LOGBOOK:
- State "DONE"       from "TODO"       [2016-07-17 Sun 17:44]
:END:
如果选择把 pdf 文件导入到该笔记中，最好自动把 tex 和 pdf 文件加入到附件中，防止在其他平台没有同步这些文件。
** TODO 对于后缀名为 .org 且附件中没有 .org 后缀名的文件的笔记，点击 org2wiz 按钮可以自动添加一个空白的 .org 文件（最好可以弹出对话框，来设定 org 文件名）
- 这里其实复用了 org2wiz 按钮的功能：如果附件中无 org 文件，自动添加 org 文件（用户设定文件名）；如果附件中有 org 文件，把 org 文件导入到笔记中
- 判断笔记后缀名是否为 .org
- 判断附件中是否有 .org 文件
- 点击 org2wiz 按钮，弹出对话框，让用户输入文件名（判断是否需要自动添加 .org 后缀）
- 判断用户输入的文件名是否为空，或者是否点了“取消”（其实这个时候提交的文件名也是空）
- 根据用户设定的文件名新建 .org 文件，并添加到笔记的附件中
** 调用 emacs 不显示命令行的黑框
可以参考 [[https://github.com/CodeFalling/hexo-renderer-org][hexo-renderer-org]]。
** org2wiz 可以在调用 emacs 时设置传递或者添加某些字串
借鉴 hexo-renderer-org 中的 common 字段。也可以同时解决导出 html 时没调用 emacs 配置文件导致的一些问题，比如 emacs 中自己配置的三种标点符号的转义：
#+BEGIN_SRC emacs-lisp
(after-load 'org
    ;; 只对某个标点禁止转义，只需要把下面这一行双引号中最后面的 \"', 这三个符号（其中双引号在配置中需要转义）中除了要禁止转义符号的其他符号加入到下面的下面那一行中
    ;; (setcar (nthcdr 2 org-emphasis-regexp-components) " \t\r\n,\"'")
    (setcar (nthcdr 2 org-emphasis-regexp-components) " \t\r\n")
    (org-set-emph-re 'org-emphasis-regexp-components org-emphasis-regexp-components)
  )
#+END_SRC
** DONE 对于后缀是 .org 且没有 .org 附件的 Document 自动添加空的 .org 附件（完成）
CLOSED: [2016-09-18 Sun 19:02]
:LOGBOOK:
- State "DONE"       from "TODO"       [2016-09-18 Sun 19:02]
:END:
* 插件已更新功能
- 去除 markdown 相关功能以及 mdExport 按钮。
- 允许 org 导入的 html 笔记中使用 js。
- 自动找到附件中的 org 文件，不需要一定在附件的第一位。
- org 生成 html 更新到笔记中之后，不再删除生成的 html 文件。
- 可以选择不在 html 中加入 MathJax 的部分，这样为知会自动调用 MathJax 进行渲染。
- 进行 Org2Wiz 转换时，自动添加一个默认标签到文档（转换之后需要切换到其他文档，再切换回来才能看到新添加的标签）。
- 一键把与 org 同名的tex 文件（或者 tex 文件与 pdf 文件）作为附件到文档（需要在工具里面设置“附件选项”值为“1”或 “2”，才会显示“AddAttach”按钮，点击该按钮可实现一键添加附件）。
- 对于后缀是 .org 且没有 .org 附件的 Document 自动添加空的 .org 附件，需提前设置好编码方式：UTF8(默认)，UTF8-BOM，GBK。
* 参考
- [[http://app.wiz.cn/index.html?id=181][org-mode插件 - 为知笔记应用中心]]
- [[http://bbs.wiz.cn/thread-17135-1-3.html][Emacs Org-Mode 插件 - 为知笔记 (Wiz)Windows 客户端帮助区 - 为知笔记 (WizNote) 帮助中心 - Powered by Discuz!]]
- [[http://bbs.wiz.cn/forum.php?mod=redirect&goto=findpost&ptid=17135&pid=109573][解决方案－为知笔记论坛]]
