#+TITLE: org2wiz
#+OPTIONS: ^:{}

* 插件介绍
为知笔记的一款插件，使为知支持 org-mode。
* 插件安装
打包下载 repo 的 zip 压缩包，然后将 ~.zip~ 后缀改为 ~.wizplugin~ ，双击安装即可。
* 插件使用
org 文档标题必须以 ~.org~ 结尾。插入附件，后缀为 ~.org~ ，然后在为知笔记界面点击 ~org2wiz~ 。

感谢原作者 [[http://bbs.wiz.cn/space-uid-5130.html][@myflocky]]。
* 原插件问题
安装原版 ~Org-Mode插件~ 之后，按照应用描述进行操作会没有一点效果，操作之后还是一片空白。好心人 [[http://bbs.wiz.cn/space-uid-26363.html][@yangguang760]] 在 [[http://bbs.wiz.cn/forum.php?mod=redirect&goto=findpost&ptid=17135&pid=109573][帖子回复]] 中指出在这里需要对 ~Org-Mode插件~ 文件夹（ ~D:\MyDocuments\My Knowledge\Plugins\{a1f84253-8cba-4753-82c9-6654642c3c8c}~ ）下的 ~Org-Mode.js~ 文件作修改，修改方法见以上引用信息。其中 ~D:\MyDocuments~ 为我在本机安装数据文件夹的路径，请自行替换为自己电脑上为知笔记的数据文件夹路径。

#+BEGIN_QUOTE
新版org-mode的内置函数改了，所以插件的第30行应改为
#+BEGIN_SRC
strParam = " --batch -q --no-site-file --visit \""+OrgFile+"\" --funcall org-html-export-to-html";
#+END_SRC
本人已验证。
#+END_QUOTE

感谢好心人 [[http://bbs.wiz.cn/space-uid-26363.html][@yangguang760]] 给出了解决方案。
* 想法
下面是我根据我的部分需求和想法想让该插件实现的功能。只可惜我对这些没有经验，但会试着学习来实现这些功能，更希望能有感兴趣的道友一起实现这些功能。
** TODO 从 org 导出的 html 也支持 MathJax(本地/远程)
+类似该插件支持的 markdown 导出之后仍然支持调用 MathJax 的功能。+ 本身已经支持本地 MathJax 解析功能。可以选择调用本地的 MathJax 还是远程的 MathJax。
** TODO 自动识别附件中需要导出的那个 org 文件
附件中有时候不会只放置所需的 org 文件，有时候会加入一些其他附件，这个时候附件的自动排序会导致插件的导入 org 功能失效。此时必须手动修改 org 文件名，很不方便，也不智能。

我的想法是：如果附件中只有一个 org 文件，就让该插件自动识别已添加的附件，并找出所需的 org 文件，然后进行 Org2Wiz 操作；如果有多个 org 文件会让使用者选择需要导出的 org 文件，否则就导出默认的那个文件（该功能还需要进行更周全的考虑）。
** TODO Org2Wiz 支持利用为知的导入 pdf 功能实现把 org 通过 tex 导出的 pdf 文件导入当前笔记中
功能构思：org 常用的导出格式为 html 和 pdf(经过 LaTeX)，而 pdf 格式对公式的支持比 MathJax 好。因此想要实现可以选择导出 html 还是导出 pdf 到该笔记中。为知支持 pdf 导入，但是好像知道只可以导入到新笔记中，需要更仔细的调研。

这个功能还涉及到 org 中针对 html 和 pdf 导出的相关设置，暂时不重点考虑，假设导出时这部分设置已经完善
** TODO 自动把当前文件夹同名的 pdf 和 tex 文件加入到附件中
如果选择把 pdf 文件导入到该笔记中，最好自动把 tex 和 pdf 文件加入到附件中，防止在其他平台没有同步这些文件。
* 参考
+ [[http://app.wiz.cn/index.html?id=181][org-mode插件 - 为知笔记应用中心]]
+ [[http://bbs.wiz.cn/thread-17135-1-3.html][Emacs Org-Mode 插件 - 为知笔记 (Wiz)Windows 客户端帮助区 - 为知笔记 (WizNote) 帮助中心 - Powered by Discuz!]]
+ [[http://bbs.wiz.cn/forum.php?mod=redirect&goto=findpost&ptid=17135&pid=109573][解决方案－为知笔记论坛]]
